name = "Finckr" 
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Add Node.js compatibility version
node_compat = true
node_version = "20.10.0" # Updated Node.js version
